# Generated by Django 6.0.2 on 2026-03-02 22:12

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du chatbot')),
                ('description', models.TextField(blank=True, help_text="Description courte pour l'admin", verbose_name='Description')),
                ('system_prompt', models.TextField(blank=True, help_text="Instructions pour le LLM. Ex: Tu es AlloGaz, assistant spécialisé en livraison de gaz. Réponds dans la langue de l'utilisateur.", verbose_name='Prompt système')),
                ('llm_model', models.CharField(default='mistral', help_text='Ex: mistral, llama3, phi3', max_length=100, verbose_name='Modèle LLM')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Chatbot',
                'verbose_name_plural': 'Chatbots',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DB principale', help_text='Ex: Base commandes AlloGaz, Base stations Maroc', max_length=100, verbose_name='Nom de la configuration')),
                ('db_engine', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('sqlite', 'SQLite')], default='postgresql', max_length=20, verbose_name='Moteur de base de données')),
                ('db_name', models.CharField(max_length=100, verbose_name='Nom de la base de données')),
                ('host', models.CharField(default='localhost', max_length=255, verbose_name='Hôte')),
                ('port', models.IntegerField(default=5432, verbose_name='Port')),
                ('username', models.CharField(max_length=100, verbose_name='Utilisateur DB')),
                ('password', models.CharField(max_length=255, verbose_name='Mot de passe DB')),
                ('allowed_tables', models.JSONField(default=list, help_text='Ex: ["stations", "fuel_stock", "prices"]', verbose_name='Tables autorisées')),
                ('db_type', models.CharField(choices=[('gaz', 'Gaz'), ('carburant', 'Carburant'), ('stations', 'Stations'), ('general', 'Général')], default='general', max_length=20, verbose_name='Type de données')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_configs', to='core.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Configuration DB',
                'verbose_name_plural': 'Configurations DB',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('file', models.FileField(upload_to=core.models.document_upload_path, verbose_name='Fichier')),
                ('doc_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word (.docx)'), ('txt', 'Texte (.txt)'), ('csv', 'CSV')], max_length=10, verbose_name='Type de document')),
                ('is_processed', models.BooleanField(default=False, help_text='Devient True après chunking et embedding', verbose_name='Traité (indexé dans Qdrant)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Document RAG',
                'verbose_name_plural': 'Documents RAG',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_response_length', models.IntegerField(default=500, verbose_name='Longueur max réponse (tokens)')),
                ('response_style', models.CharField(choices=[('concise', 'Concis'), ('formal', 'Formel'), ('friendly', 'Friendly')], default='concise', max_length=20, verbose_name='Style de réponse')),
                ('chatbot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='core.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Scope (Paramètres)',
                'verbose_name_plural': 'Scopes (Paramètres)',
            },
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('sql', 'SQL Agent'), ('rag', 'RAG Agent'), ('arithmetic', 'Arithmetic Agent'), ('custom', 'Agent personnalisé')], max_length=50, verbose_name="Type d'agent")),
                ('enabled', models.BooleanField(default=True, verbose_name='Activé')),
                ('priority', models.IntegerField(default=1, help_text="Ordre d'appel des agents. 1 = premier", verbose_name='Priorité')),
                ('llm_model', models.CharField(choices=[('qwen3:8b', 'qwen3:8b  — Logique & SQL'), ('gemma3', 'gemma3   — RAG & Génération NL'), ('phi4', 'phi4     — Calculs & Tâches légères')], default='qwen3:8b', help_text='Modèle utilisé par cet agent spécifiquement', max_length=100, verbose_name='Modèle LLM')),
                ('agent_prompt', models.TextField(blank=True, help_text="Instructions techniques spécifiques à cet agent. Ex pour SQL: 'Génère uniquement des SELECT. Tables autorisées: {tables}'", verbose_name="Prompt technique de l'agent")),
                ('config', models.JSONField(blank=True, default=dict, help_text='Ex: {"max_rows": 100, "timeout": 30}', verbose_name='Configuration spécifique')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['priority'],
                'unique_together': {('chatbot', 'agent_type')},
            },
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ID Utilisateur')),
                ('key', models.CharField(help_text='Ex: fuel_type, location, quantity', max_length=100, verbose_name='Clé')),
                ('value', models.TextField(help_text='Ex: diesel, Maarif, 3', verbose_name='Valeur')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.chatbot', verbose_name='Chatbot')),
            ],
            options={
                'verbose_name': 'Mémoire Conversation',
                'verbose_name_plural': 'Mémoires Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('user_id', 'chatbot', 'key')},
            },
        ),
    ]
