# Generated by Django 6.0.3 on 2026-03-07 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '🔴 Administrateur'), ('editor', '🟡 Éditeur'), ('viewer', '⚪ Lecteur')], default='viewer', max_length=20)),
                ('allowed_chatbots', models.ManyToManyField(blank=True, to='core.chatbot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
            },
        ),
    ]
