# Generated by Django 6.0.3 on 2026-03-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100, verbose_name='Nom de la plateforme')),
                ('keycloak_url', models.CharField(default='http://keycloak:8080', max_length=255)),
                ('keycloak_realm', models.CharField(max_length=100, verbose_name='Realm Keycloak')),
                ('keycloak_client_id', models.CharField(max_length=100, verbose_name='Client ID frontend')),
                ('keycloak_audience', models.CharField(max_length=100, verbose_name='Audience backend')),
                ('keycloak_client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('jwks_cache_ttl', models.IntegerField(default=3600, verbose_name='TTL cache JWKS (s)')),
                ('orchestrator_url', models.CharField(default='http://orchestrator:8000', max_length=255)),
                ('redis_url', models.CharField(default='redis://redis:6379', max_length=255)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuration plateforme',
                'verbose_name_plural': 'Configurations plateforme',
            },
        ),
        migrations.AddField(
            model_name='chatbot',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Si coché, ce chatbot sera automatiquement assigné à tout nouveau client lors de sa première connexion', verbose_name='Chatbot par défaut'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='keycloak_id',
            field=models.CharField(blank=True, help_text="Le 'sub' du JWT Keycloak — copié depuis la console Keycloak → Users → ID", max_length=255, null=True, unique=True, verbose_name='UUID Keycloak'),
        ),
    ]
