# Generated by Django 6.0.3 on 2026-03-22 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_platformconfig_chatbot_is_default_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlatformConfig',
        ),
    ]
