# Generated by Django 5.0.3 on 2026-03-30 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chatbot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "role",
                    models.TextField(
                        help_text="System prompt defining the chatbot's role and behavior"
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True,
                        help_text="Guardrails and boundaries for the chatbot",
                    ),
                ),
                (
                    "base_model",
                    models.CharField(
                        choices=[
                            ("qwen3:8b", "Qwen3:8b"),
                            ("qwen2.5:7b", "Qwen2.5:7b"),
                            ("Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct"),
                            (
                                "Qwen/Qwen3-Coder-32B-Instruct",
                                "Qwen/Qwen3-Coder-32B-Instruct",
                            ),
                            ("gemma3", "Gemma3"),
                            ("phi4", "Phi4"),
                            ("llama3.2:3b", "Llama 3.2 3B"),
                        ],
                        default="qwen3:8b",
                        max_length=100,
                    ),
                ),
                ("sql_enabled", models.BooleanField(default=False)),
                ("rag_enabled", models.BooleanField(default=False)),
                ("action_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chatbot",
                "verbose_name_plural": "Chatbots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActionAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(help_text="Description of what this action does"),
                ),
                (
                    "endpoint",
                    models.URLField(
                        max_length=1024,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                        ],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="HTTP headers as JSON object",
                    ),
                ),
                (
                    "payload_template",
                    models.JSONField(
                        blank=True, default=dict, help_text="Request payload template"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="dashboard.chatbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RAGAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "use_reranker",
                    models.BooleanField(
                        default=False,
                        help_text="Enable semantic reranking of retrieved documents",
                    ),
                ),
                (
                    "use_query_expansion",
                    models.BooleanField(
                        default=False,
                        help_text="Expand queries with synonyms and related terms",
                    ),
                ),
                (
                    "top_k",
                    models.IntegerField(
                        default=5, help_text="Number of top documents to retrieve"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="sentence-transformers/all-MiniLM-L6-v2", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chatbot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_config",
                        to="dashboard.chatbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG Configuration",
                "verbose_name_plural": "RAG Configurations",
            },
        ),
        migrations.CreateModel(
            name="DocumentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("fiche_technique", "Fiche Technique"),
                            ("faq", "FAQ"),
                            ("manual", "Manual"),
                            ("report", "Report"),
                            ("guide", "Guide"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of document for RAG classification",
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                (
                    "url",
                    models.URLField(
                        blank=True, validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("is_indexed", models.BooleanField(default=False)),
                (
                    "chunks_indexed",
                    models.IntegerField(
                        default=0, help_text="Number of chunks indexed by RAG agent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rag_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dashboard.ragagent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Reference",
                "verbose_name_plural": "Document References",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SQLAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Connection identifier (e.g., 'flight_db_01')",
                        max_length=255,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        help_text="Human-readable database name (e.g., 'Global Flight Operations')",
                        max_length=255,
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("postgresql", "PostgreSQL"),
                            ("mysql", "MySQL"),
                            ("sqlite", "SQLite"),
                            ("mssql", "Microsoft SQL Server"),
                            ("oracle", "Oracle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "connection_string",
                    models.CharField(
                        help_text="Database connection URI (e.g., 'sqlite:///path/to/db.sqlite')",
                        max_length=1024,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sql_connections",
                        to="dashboard.chatbot",
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Connection",
                "verbose_name_plural": "SQL Connections",
                "ordering": ["name"],
            },
        ),
    ]
