# Generated by Django 5.0.3 on 2026-03-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_add_gateway_fields"),
        ("dashboard", "0002_alter_chatbot_base_model"),
    ]

    operations = []
