# Generated by Django 5.0.3 on 2026-03-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sqlagent_llm"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="sql_llm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qwen3:8b", "Qwen3:8b"),
                    ("qwen2.5:7b", "Qwen2.5:7b"),
                    ("Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct"),
                    ("Qwen/Qwen3-Coder-32B-Instruct", "Qwen/Qwen3-Coder-32B-Instruct"),
                    ("gemma3", "Gemma3"),
                    ("phi4", "Phi4"),
                    ("llama3.2:3b", "Llama 3.2 3B"),
                ],
                default="Qwen/Qwen2.5-7B-Instruct",
                help_text="LLM used by SQL agent for all database connections",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sqlagent",
            name="llm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("qwen3:8b", "Qwen3:8b"),
                    ("qwen2.5:7b", "Qwen2.5:7b"),
                    ("Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct"),
                    ("Qwen/Qwen3-Coder-32B-Instruct", "Qwen/Qwen3-Coder-32B-Instruct"),
                    ("gemma3", "Gemma3"),
                    ("phi4", "Phi4"),
                    ("llama3.2:3b", "Llama 3.2 3B"),
                ],
                default="Qwen/Qwen2.5-7B-Instruct",
                help_text="(Deprecated - use chatbot.sql_llm instead)",
                max_length=100,
                null=True,
            ),
        ),
    ]
