# Generated by Django 5.0.3 on 2026-04-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_chatbot_sql_llm_alter_sqlagent_llm'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as default chatbot for API consumers'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='location_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='rag_agent_prompt',
            field=models.TextField(blank=True, help_text='Custom instructions for RAG agent'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='rag_llm',
            field=models.CharField(blank=True, choices=[('qwen3:8b', 'Qwen3:8b'), ('qwen2.5:7b', 'Qwen2.5:7b'), ('Qwen/Qwen2.5-7B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'), ('Qwen/Qwen3-Coder-32B-Instruct', 'Qwen/Qwen3-Coder-32B-Instruct'), ('gemma3', 'Gemma3'), ('phi4', 'Phi4'), ('llama3.2:3b', 'Llama 3.2 3B')], help_text='LLM used by RAG agent (uses base_model if not specified)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='sql_agent_prompt',
            field=models.TextField(blank=True, help_text="Custom instructions for SQL agent (e.g., 'Only generate SELECT queries')"),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='weather_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ragagent',
            name='agent_prompt',
            field=models.TextField(blank=True, help_text="Custom instructions for RAG agent (e.g., 'Only answer from provided documents')"),
        ),
        migrations.AddField(
            model_name='ragagent',
            name='qdrant_collection',
            field=models.CharField(blank=True, help_text='Qdrant collection name for vector storage', max_length=255),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='agent_prompt',
            field=models.TextField(blank=True, help_text='Custom instructions for SQL queries on this connection'),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='allowed_tables',
            field=models.JSONField(blank=True, default=list, help_text='List of tables the agent is allowed to query'),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
