# Generated by Django 5.0.3 on 2026-04-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_chatbot_is_default_chatbot_location_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='location_enabled',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='rag_agent_prompt',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='rag_llm',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='sql_agent_prompt',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='weather_enabled',
        ),
        migrations.RemoveField(
            model_name='ragagent',
            name='agent_prompt',
        ),
        migrations.RemoveField(
            model_name='ragagent',
            name='qdrant_collection',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='agent_prompt',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='allowed_tables',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='host',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='password',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='port',
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='username',
        ),
    ]
