# Generated by Django 5.0.3 on 2026-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_chatbot_base_model_alter_chatbot_sql_llm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentreference',
            options={'ordering': ['name'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='ragagent',
            options={'verbose_name': 'Configuration RAG', 'verbose_name_plural': 'Configurations RAG'},
        ),
        migrations.AlterModelOptions(
            name='sqlagent',
            options={'ordering': ['name'], 'verbose_name': 'Connexion SQL', 'verbose_name_plural': 'Connexions SQL'},
        ),
        migrations.AddField(
            model_name='ragagent',
            name='agent_description',
            field=models.TextField(blank=True, default='', help_text="Décris les documents indexés dans ce RAG. Utilisé par le router pour choisir cet agent. Ex: 'Contient les fiches techniques huiles moteur (Qualix, Havoline, Delo), normes API/ACEA, spécifications viscosité et guides d\\'utilisation.'"),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='agent_description',
            field=models.TextField(blank=True, default='', help_text="Décris ce que contient cette base de données. Utilisé par le router pour choisir cet agent. Ex: 'Contient les stations-service, prix carburant, coordonnées GPS, historique commandes et produits disponibles.'"),
        ),
        migrations.AlterField(
            model_name='actionagent',
            name='description',
            field=models.TextField(help_text="Décris ce que fait cette action ET quand le router doit l'utiliser. Ex: 'Envoie une notification SMS au client. À utiliser quand l\\'utilisateur demande un rappel, une confirmation ou un code de vérification.'"),
        ),
        migrations.AlterField(
            model_name='actionagent',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='actionagent',
            name='payload_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='role',
            field=models.TextField(help_text='System prompt définissant le rôle et le comportement du chatbot'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='scope',
            field=models.TextField(blank=True, help_text='Guardrails et limites du chatbot'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='sql_llm',
            field=models.CharField(blank=True, choices=[('qwen3:8b', 'Qwen3:8b'), ('qwen2.5:7b', 'Qwen2.5:7b'), ('Qwen/Qwen2.5-7B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'), ('Qwen/Qwen3-Coder-32B-Instruct', 'Qwen/Qwen3-Coder-32B-Instruct'), ('gemma3', 'Gemma3'), ('phi4', 'Phi4'), ('llama3.2:3b', 'Llama 3.2 3B'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)')], default='Qwen/Qwen2.5-7B-Instruct', help_text="LLM utilisé par l'agent SQL pour toutes les connexions", max_length=100),
        ),
        migrations.AlterField(
            model_name='documentreference',
            name='chunks_indexed',
            field=models.IntegerField(default=0, help_text='Nombre de chunks indexés'),
        ),
        migrations.AlterField(
            model_name='documentreference',
            name='doc_type',
            field=models.CharField(choices=[('fiche_technique', 'Fiche Technique'), ('faq', 'FAQ'), ('manual', 'Manual'), ('report', 'Report'), ('guide', 'Guide'), ('other', 'Other')], default='other', help_text='Type de document pour la classification RAG', max_length=50),
        ),
        migrations.AlterField(
            model_name='ragagent',
            name='top_k',
            field=models.IntegerField(default=5, help_text='Nombre de documents à récupérer'),
        ),
        migrations.AlterField(
            model_name='ragagent',
            name='use_query_expansion',
            field=models.BooleanField(default=False, help_text='Étendre les requêtes avec synonymes et termes associés'),
        ),
        migrations.AlterField(
            model_name='ragagent',
            name='use_reranker',
            field=models.BooleanField(default=False, help_text='Activer le reranking sémantique des documents récupérés'),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='connection_string',
            field=models.CharField(help_text="URI de connexion (ex: 'sqlite:///path/to/db.sqlite')", max_length=1024),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='db_name',
            field=models.CharField(help_text="Nom lisible de la base (ex: 'Base Stations Afriquia')", max_length=255),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='llm',
            field=models.CharField(blank=True, choices=[('qwen3:8b', 'Qwen3:8b'), ('qwen2.5:7b', 'Qwen2.5:7b'), ('Qwen/Qwen2.5-7B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'), ('Qwen/Qwen3-Coder-32B-Instruct', 'Qwen/Qwen3-Coder-32B-Instruct'), ('gemma3', 'Gemma3'), ('phi4', 'Phi4'), ('llama3.2:3b', 'Llama 3.2 3B'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)')], default='Qwen/Qwen2.5-7B-Instruct', help_text='(Déprécié - utiliser chatbot.sql_llm)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='name',
            field=models.CharField(help_text="Identifiant de la connexion (ex: 'stations_db')", max_length=255),
        ),
    ]
