# Generated by Django 5.0.3 on 2026-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
