# Generated by Django 5.0.3 on 2026-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_userprofile_supabase_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqlagent',
            options={'ordering': ['name'], 'verbose_name': 'SQL Connection', 'verbose_name_plural': 'SQL Connections'},
        ),
        migrations.RemoveField(
            model_name='sqlagent',
            name='agent_description',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='location_enabled',
            field=models.BooleanField(default=False, help_text="Activer l'agent de géolocalisation (station la plus proche)", verbose_name='Location Agent'),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='weather_enabled',
            field=models.BooleanField(default=False, help_text="Activer l'agent météo (température, pluie, vent)", verbose_name='Weather Agent'),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='database',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='sqlite_path',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='sqlagent',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='connection_string',
            field=models.CharField(blank=True, help_text='Legacy connection URI (auto-generated from individual fields)', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='db_name',
            field=models.CharField(help_text="Human-readable database name (e.g., 'Global Flight Operations')", max_length=255),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='llm',
            field=models.CharField(blank=True, choices=[('qwen3:8b', 'Qwen3:8b'), ('qwen2.5:7b', 'Qwen2.5:7b'), ('Qwen/Qwen2.5-7B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'), ('Qwen/Qwen3-Coder-32B-Instruct', 'Qwen/Qwen3-Coder-32B-Instruct'), ('gemma3', 'Gemma3'), ('phi4', 'Phi4'), ('llama3.2:3b', 'Llama 3.2 3B'), ('llama-3.3-70b-versatile', 'Llama 3.3 70B (Groq)')], default='Qwen/Qwen2.5-7B-Instruct', help_text='(Deprecated - use chatbot.sql_llm instead)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sqlagent',
            name='name',
            field=models.CharField(help_text="Connection identifier (e.g., 'flight_db_01')", max_length=255),
        ),
    ]
