# Generated by Django 5.0.3 on 2026-04-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_sqlagent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlagent',
            name='agent_description',
            field=models.TextField(blank=True, default='', help_text="Schéma DB, mapping codes produits, règles SQL. Utilisé par l'orchestrateur."),
        ),
    ]
